### ISSUE TITLE
Milestone 4 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/air-pollution#66]
> **Congratulations on finishing milestone 4!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. Submission instructions
rubric={mechanics:4}
Well done!

## 2. Improving your app
rubric={mechanics:20}
Well done!

#### 2.1 - Testing
rubric={mechanics:5, accuracy:5}

- The tests are not passing in the github action workflow `testing.yaml` **-2.5 accuracy**
![Screen Shot 2023-03-24 at 7 30 52 AM](https://user-images.githubusercontent.com/86759356/227558483-68694b84-c8c2-4e0e-a5e2-e1346995f1ae.png)

#### 2.2 Continous Integration and Deployment
rubric={mechanics:5, accuracy:5}

- [ ] There are no badges in the `README.md`. There should be one workflow badge **-5 mechanics**

- [ ] The deployment workflow `deploy_app.yaml` is not passing. **-5 accuracy**

## 3. Tie it all together and deliver a production ready app
rubric={mechanics:20, accuracy:20, viz:10}

**You are creating your production-ready Shiny app this week!**
Well done!

**Improve the user feedback**
Well done!

**Improve the documentation**
The GitHub repo description in the top right corner where it says “About”:
- [ ] The deployment of the app is not working or is giving errors. Parts of the app seem missing or fail. **-4 mechanics**

Comments: 
- I encountered an error:
![Screen Shot 2023-03-24 at 7 39 40 AM](https://user-images.githubusercontent.com/86759356/227558565-66dec93f-18f7-4491-8267-d9a4213793fd.png)

- It might be because of the size of the data but I needed to start over multiple times while working with the app as the page was stopping responding. I did not penalize you for it as it can be due to my system but there might be room for improving user experience there. 

## 4. Reflection
rubric={reasoning:6}
Well done!
